spring:
  application:
    name: web
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/webdb
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
  # JDBC configuration for Flyway
  datasource:
    url: jdbc:postgresql://localhost:5432/webdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/webdb
    user: postgres
    password: postgres

server:
  port: 8080