services:
  postgres:
    image: postgres:17
    container_name: web-postgres
    environment:
      POSTGRES_DB: webdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 1
      start_interval: 1s
      start_period: 1s

volumes:
  postgres_data:
